website/accounts/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, FloatField, StringField, SubmitField
from wtforms.validators import DataRequired


class AccountForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()])
    type = StringField("Type", validators=[DataRequired()])
    bank = StringField("Bank", validators=[DataRequired()])
    acc_num = StringField("Account No.", validators=[DataRequired()])
    credit_card = BooleanField("Is this a credit card?")
    investment = BooleanField("Is this a investment?")
    amount = FloatField("Amount", validators=[DataRequired()])
    submit = SubmitField("Create")

website/budgets/forms.py
from flask_wtf import FlaskForm
from wtforms import FloatField, SelectField, StringField, SubmitField
from wtforms.validators import DataRequired


class BudgetForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()])
    initial = FloatField("Budget", validators=[DataRequired()])
    present = FloatField("Used", validators=[DataRequired()])
    tenure = SelectField(
        "Frequency",
        choices=[("monthly", "monthly"), ("yearly", "yearly"), ("nolimit", "no limit")],
    )
    submit = SubmitField("Create")

website/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    content = TextAreaField("Content", validators=[DataRequired()])
    submit = SubmitField("Post")

website/accounts/routes.py
from datetime import datetime, timedelta

from flask import (
    Blueprint,
    abort,
    flash,
    jsonify,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required
from website import db
from website.accounts.forms import AccountForm
from website.models import Account

accounts = Blueprint("accounts", __name__)


@accounts.route("/accounts")
@login_required
def show_accounts():
    accs = Account.query.filter_by(user_id=current_user.id).all()
    return render_template("accounts.html", accounts=accs)


@accounts.route("/api/accounts", methods=["GET"])
@login_required
def get_accounts():
    """
    Api to get a list of all accounts
    """
    accs = Account.query.filter_by(user_id=current_user.id).all()

    data = []
    for acc in accs:
        data.append(
            {
                "id": acc.id,
                "name": acc.name,
                "date": acc.date,
                "type": acc.type,
                "bank": acc.bank,
                "acc_num": acc.acc_num,
                "credit_card": acc.credit_card,
                "investment": acc.investment,
                "amount": acc.amount,
            }
        )
    return jsonify({"data": data})


@accounts.route("/accounts/new", methods=["GET", "POST"])
@login_required
def new_account():
    form = AccountForm()
    if form.validate_on_submit():
        acc = Account(
            name=form.name.data,
            type=form.type.data,
            bank=form.bank.data,
            acc_num=form.acc_num.data,
            credit_card=form.credit_card.data,
            investment=form.investment.data,
            amount=form.amount.data,
            acc_holder=current_user,
            date=datetime.utcnow() + timedelta(hours=5, minutes=30),
        )

        db.session.add(acc)
        db.session.commit()
        flash("Your account has been created!", "success")
        return redirect(url_for("accounts.show_accounts"))
    return render_template(
        "create_account.html", title="New Account", form=form, legend="New Account"
    )


@accounts.route("/accounts/<int:acc_id>")
@login_required
def read_acc(acc_id):
    acc = Account.query.filter_by(user_id=current_user.id).get_or_404(acc_id)
    return render_template("acc.html", title=acc.name, post=acc)


@accounts.route("/accounts/<int:acc_id>/update", methods=["GET", "POST"])
@login_required
def update_account(acc_id):
    account = Account.query.filter_by(id=acc_id).first()
    if account.user_id != current_user.id:
        abort(403)
    form = AccountForm()
    if form.validate_on_submit():
        account.name = form.name.data
        account.type = form.type.data
        account.bank = form.bank.data
        account.acc_num = form.acc_num.data
        account.credit_card = form.credit_card.data
        account.investment = form.investment.data
        account.amount = form.amount.data
        account.date = datetime.utcnow() + timedelta(hours=5, minutes=30)
        db.session.commit()
        flash("Your account has been updated!", "success")
        return redirect(url_for("accounts.show_accounts"))
    elif request.method == "GET":
        form.name.data = account.name
        form.type.data = account.type
        form.bank.data = account.bank
        form.acc_num.data = account.acc_num
        form.credit_card.data = account.credit_card
        form.investment.data = account.investment
        form.amount.data = account.amount
        form.submit.label.text = "Update"

    return render_template(
        "create_account.html",
        title="Update Account",
        form=form,
        legend="Update Account",
    )


@accounts.route("/accounts/<int:acc_id>/delete", methods=["POST"])
@login_required
def delete_account(acc_id):
    account = Account.query.filter_by(id=acc_id).first()
    if account.user_id != current_user.id:
        abort(403)
    db.session.delete(account)
    db.session.commit()
    flash("Your account has been deleted!", "success")
    return redirect(url_for("accounts.show_accounts"))

website/budgets/routes.py
from datetime import datetime, timedelta

from flask import (
    Blueprint,
    abort,
    flash,
    jsonify,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required
from website import db
from website.budgets.forms import BudgetForm
from website.models import Budget

budgets = Blueprint("budgets", __name__)


@budgets.route("/budgets")
@login_required
def show_budgets():
    budgets = Budget.query.filter_by(user_id=current_user.id).all()
    return render_template("budgets.html", budgets=budgets)


@budgets.route("/api/budgets", methods=["GET"])
@login_required
def get_budgets():
    """
    Api to get a list of all budgets
    """
    budgets = Budget.query.filter_by(user_id=current_user.id).all()

    data = []
    for budget in budgets:
        data.append(
            {
                "id": budget.id,
                "name": budget.name,
                "date": budget.date,
                "initial": budget.initial,
                "present": budget.present,
                "tenure": budget.tenure.name,
            }
        )
    return jsonify({"data": data})


@budgets.route("/budgets/new", methods=["GET", "POST"])
@login_required
def new_budget():
    form = BudgetForm()
    if form.validate_on_submit():
        budget = Budget(
            name=form.name.data,
            initial=form.initial.data,
            present=form.present.data,
            tenure=form.tenure.data,
            acc_holder=current_user,
            date=datetime.utcnow() + timedelta(hours=5, minutes=30),
        )

        db.session.add(budget)
        db.session.commit()
        flash("Your budget has been created!", "success")
        return redirect(url_for("budgets.show_budgets"))
    return render_template(
        "create_budget.html", title="New Budget", form=form, legend="New Budget"
    )


@budgets.route("/budgets/<int:budget_id>/update", methods=["GET", "POST"])
@login_required
def update_budget(budget_id):
    budget = Budget.query.filter_by(id=budget_id).first()
    if budget.user_id != current_user.id:
        abort(403)
    form = BudgetForm()
    if form.validate_on_submit():
        budget.name = form.name.data
        budget.initial = form.initial.data
        budget.present = form.present.data
        budget.tenure = form.tenure.data
        budget.date = datetime.utcnow() + timedelta(hours=5, minutes=30)
        db.session.commit()
        flash("Your budget has been updated!", "success")
        return redirect(url_for("budgets.show_budgets"))
    elif request.method == "GET":
        form.name.data = budget.name
        form.initial.data = budget.initial
        form.present.data = budget.present
        form.tenure.data = budget.tenure
        form.submit.label.text = "Update"

    return render_template(
        "create_budget.html",
        title="Update budget",
        form=form,
        legend="Update budget",
    )


@budgets.route("/budgets/<int:budget_id>/delete", methods=["POST"])
@login_required
def delete_budget(budget_id):
    budget = Budget.query.filter_by(id=budget_id).first()
    if budget.user_id != current_user.id:
        abort(403)
    db.session.delete(budget)
    db.session.commit()
    flash("Your budget has been deleted!", "success")
    return redirect(url_for("budgets.show_budgets"))

website/posts/routes.py
from flask import Blueprint, abort, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from website import db
from website.posts.forms import PostForm
from website.models import Post

posts = Blueprint("posts", __name__)


@posts.route("/post/new", methods=["GET", "POST"])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(
            title=form.title.data, content=form.content.data, author=current_user
        )
        db.session.add(post)
        db.session.commit()
        flash("Your post has been created!", "success")
        return redirect(url_for("main.home"))
    return render_template(
        "create_post.html", title="New Post", form=form, legend="New Post"
    )


@posts.route("/post/<int:post_id>")
def view_post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template("view_post.html", title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=["GET", "POST"])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash("Your post has been updated!", "success")
        return redirect(url_for("posts.view_post", post_id=post.id))
    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content
    return render_template(
        "create_post.html", title="Update Post", form=form, legend="Update Post"
    )


@posts.route("/post/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("Your post has been deleted!", "success")
    return redirect(url_for("main.home"))

website/users/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from website import bcrypt, db
from website.users.forms import (
    LoginForm,
    RegistrationForm,
    RequestResetForm,
    ResetPasswordForm,
    UpdateAccountForm,
)
from website.models import Post, User
from website.users.utils import save_picture, send_reset_email

users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user = User(
            username=form.username.data, email=form.email.data, password=hashed_password
        )
        db.session.add(user)
        db.session.commit()
        flash("Your account has been created! You are now able to log in", "success")
        return redirect(url_for("users.login"))
    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")
            return redirect(next_page) if next_page else redirect(url_for("main.home"))
        else:
            flash("Login Unsuccessful. Please check email and password", "danger")
    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))


@users.route("/view_user", methods=["GET", "POST"])
@login_required
def view_user():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been updated!", "success")
        return redirect(url_for("users.view_user"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for("static", filename="profile_pics/" + current_user.image_file)
    return render_template(
        "view_user.html", title="Account", image_file=image_file, form=form
    )


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = (
        Post.query.filter_by(author=user)
        .order_by(Post.date_posted.desc())
        .paginate(page=page, per_page=5)
    )
    return render_template("user_posts.html", posts=posts, user=user)


@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash(
            "An email has been sent with instructions to reset your password.", "info"
        )
        return redirect(url_for("users.login"))
    return render_template("reset_request.html", title="Reset Password", form=form)


@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    user = User.verify_reset_token(token)
    if user is None:
        flash("That is an invalid or expired token", "warning")
        return redirect(url_for("users.reset_request"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user.password = hashed_password
        db.session.commit()
        flash("Your password has been updated! You are now able to log in", "success")
        return redirect(url_for("users.login"))
    return render_template("reset_token.html", title="Reset Password", form=form)

website/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

website/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

website/templates/budgets.html
{% extends "layout.html" %}
{% block content %}
<h1>Budgets Page</h1>

{% for budget in budgets %}
<article class="media content-section">
    <div class="media-body">
        <div class="card-body  p-3">
            <div class="d-flex flex-row flex-wrap align-items-start justify-content-between">
                <div>
                    <p class="fw-500 fs-18 mb-0">
                    <h4>{{budget.name}}
                    </h4>
                    </p>
                </div>
                <div>
                    <div>
                        <a href="{{ url_for('budgets.update_budget', budget_id=budget.id) }}">Update</a>
                    </div>
                    <div>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal"
                            data-target="#deleteModal{{budget.id}}">Delete</button>
                    </div>
                </div>
            </div>

            <div class="d-flex flex-wrap justify-content-between">
                <div class="false mb-2">
                    <p class="mb-0 fs-12 text-muted">Initial</p>
                    <p class="fw-500 fs-18 mb-0 mt-1">{{ budget.initial }}</p>
                </div>
                <div class="false mb-2">
                    <p class="mb-0 fs-12 text-muted">Present</p>
                    <p class="fw-500 fs-18 mb-0 mt-1">{{ budget.present }}</p>
                </div>
                <div class="false mb-2">
                    <p class="mb-0 fs-12 text-muted">Tenure</p>
                    <p class="fw-500 fs-18 mb-0 mt-1">{{ budget.tenure.name.title() }}</p>
                </div>
                <div class="false mb-2">
                    <p class="mb-0 fs-12 text-muted">Last Updated</p>
                    <p class="fw-500 fs-18 mb-0 mt-1">{{ budget.date.strftime('%d-%b-%y %-I:%M %p') }}</p>
                </div>
                <div class="mb-2"></div>
            </div>
        </div>

    </div>
</article>
<!-- Modal -->
<div class="modal fade" id="deleteModal{{budget.id}}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Budget?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('budgets.delete_budget', budget_id=budget.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock content %}

website/templates/create_budget.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.name.label(class="form-control-label") }}
                {% if form.name.errors %}
                {{ form.name(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.name.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.name(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.initial.label(class="form-control-label") }}
                {% if form.initial.errors %}
                {{ form.initial(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.initial.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.initial(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.present.label(class="form-control-label") }}
                {% if form.present.errors %}
                {{ form.present(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.present.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.present(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.tenure.label(class="form-control-label") }}
                {% if form.tenure.errors %}
                {{ form.tenure(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.tenure.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.tenure(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

website/templates/home.html
{% extends "layout.html" %}
{% block content %}
{% for post in posts.items %}
<article class="media content-section">
  <img class="rounded-circle article-img"
    src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username
        }}</a>
      <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
    </div>
    <h2><a class="article-title" href="{{ url_for('posts.view_post', post_id=post.id) }}">{{ post.title }}</a></h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
{% if posts.page == page_num %}
<a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
{% else %}
<a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
{% endif %}
{% else %}
...
{% endif %}
{% endfor %}
{% endblock content %}

website/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
            </small>
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
    </small>
</div>
{% endblock content %}

website/templates/post.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section">
  <img class="rounded-circle article-img"
    src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username
        }}</a>
      <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
      {% if post.author == current_user %}
      <div>
        <a class="btn btn-secondary btn-sm mt-1 mb-1"
          href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal"
          data-target="#deleteModal">Delete</button>
      </div>
      {% endif %}
    </div>
    <h2 class="article-title">{{ post.title }}</h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
          <input class="btn btn-danger" type="submit" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

website/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
<h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
{% for post in posts.items %}
<article class="media content-section">
  <img class="rounded-circle article-img"
    src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username
        }}</a>
      <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
    </div>
    <h2><a class="article-title" href="{{ url_for('posts.view_post', post_id=post.id) }}">{{ post.title }}</a></h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
{% if posts.page == page_num %}
<a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num
  }}</a>
{% else %}
<a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{
  page_num }}</a>
{% endif %}
{% else %}
...
{% endif %}
{% endfor %}
{% endblock content %}